import { MenuItem } from "@/types";

export const SEED_MENU: MenuItem[] = [
  {
    id: "1",
    name: "Masala Dosa",
    description: "Crispy rice crepe with spiced potato filling, served with chutney and sambar",
    price: 60,
    category: "breakfast",
    image: "🥞",
    available: true,
    prepTime: 15,
  },
  {
    id: "2",
    name: "Idli Sambar",
    description: "Soft steamed rice cakes with lentil soup and coconut chutney",
    price: 40,
    category: "breakfast",
    image: "🍚",
    available: true,
    prepTime: 10,
  },
  {
    id: "3",
    name: "Poha",
    description: "Flattened rice cooked with onions, peanuts, and spices",
    price: 35,
    category: "breakfast",
    image: "🥣",
    available: true,
    prepTime: 10,
  },
  {
    id: "4",
    name: "Veg Thali",
    description: "Complete meal with rice, dal, vegetables, roti, and dessert",
    price: 120,
    category: "lunch",
    image: "🍱",
    available: true,
    prepTime: 20,
  },
  {
    id: "5",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice with tender chicken and aromatic spices",
    price: 150,
    category: "lunch",
    image: "🍛",
    available: true,
    prepTime: 25,
  },
  {
    id: "6",
    name: "Paneer Butter Masala",
    description: "Cottage cheese in rich tomato gravy with naan",
    price: 130,
    category: "lunch",
    image: "🧀",
    available: true,
    prepTime: 20,
  },
  {
    id: "7",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 20,
    category: "snacks",
    image: "🥟",
    available: true,
    prepTime: 5,
  },
  {
    id: "8",
    name: "Veg Sandwich",
    description: "Fresh vegetables with mint chutney on toasted bread",
    price: 45,
    category: "snacks",
    image: "🥪",
    available: true,
    prepTime: 8,
  },
  {
    id: "9",
    name: "French Fries",
    description: "Golden crispy potato fries with ketchup",
    price: 50,
    category: "snacks",
    image: "🍟",
    available: true,
    prepTime: 8,
  },
  {
    id: "10",
    name: "Masala Chai",
    description: "Traditional spiced Indian tea with milk",
    price: 15,
    category: "beverages",
    image: "☕",
    available: true,
    prepTime: 5,
  },
  {
    id: "11",
    name: "Fresh Lime Soda",
    description: "Refreshing lime juice with soda and mint",
    price: 30,
    category: "beverages",
    image: "🍋",
    available: true,
    prepTime: 3,
  },
  {
    id: "12",
    name: "Cold Coffee",
    description: "Chilled coffee blended with ice cream",
    price: 45,
    category: "beverages",
    image: "🥤",
    available: true,
    prepTime: 5,
  },
  {
    id: "13",
    name: "Gulab Jamun",
    description: "Soft milk dumplings soaked in rose-flavored syrup",
    price: 40,
    category: "desserts",
    image: "🍡",
    available: true,
    prepTime: 2,
  },
  {
    id: "14",
    name: "Ice Cream Sundae",
    description: "Vanilla ice cream with chocolate sauce and nuts",
    price: 55,
    category: "desserts",
    image: "🍨",
    available: true,
    prepTime: 3,
  },
];
